---
abstract: "API for Amazon's Elastic Map-Reduce service"
author:
  - 'Jon Schutz <jon.schutz@youramigo.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Amazon-EMR
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  DateTime: 0
  DateTime::Format::ISO8601: 0
  Digest::SHA: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Moose: 0.38
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  Net::Amazon::EC2: 0.22
  POSIX: 0
  Params::Validate: 0
  Test::More: 0
  URI: 0
  URI::Escape: 0
  XML::Simple: 2.18
version: 0.10
